module Round_key_gen(
    input wire [127:0] keyin,
    input wire [3:0]r_num,
    output wire [127:0] keyout);
    
    wire [31:0] W0,W1,W2,W3;
    reg [31:0] rcon; //Round constant used depending on round number
    
    //128 bit key is split into 4 words of 4 bytes each
    assign W0=keyin[127:96];
    assign W1=keyin[95:64];
    assign W2=keyin[63:32];
    assign W3=keyin[31:0];
    
    wire [31:0]rotw3; //rotated W3
    wire [7:0] sub30,sub31,sub32,sub33; //Sbox output for each byte of W3
    wire [31:0] temp; //SubWord ^ round constant
    
    wire [31:0] w0_out,w1_out,w2_out,w3_out; //Words after key expansion operations, joined to make output key
    
    always @(*)begin
        case(r_num) //rcon values generated by repeatedly multiplying by 2 in GF field
            1 : rcon = 32'h01000000;
            2 : rcon = 32'h02000000;
            3 : rcon = 32'h04000000;
            4 : rcon = 32'h08000000;
            5 : rcon = 32'h10000000;
            6 : rcon = 32'h20000000;
            7 : rcon = 32'h40000000;
            8 : rcon = 32'h80000000;
            9 : rcon = 32'h1B000000;
            10: rcon = 32'h36000000;
            
            default: rcon=32'h00000000;
        endcase
    end
    
     assign rotw3 = {W3[23:0],W3[31:24]}; //RotWord of W3
     
     //SubWord each byte of rotated W3
     Sbox_LUT x1(.din(rotw3[31:24]), .dout(sub30));
     Sbox_LUT x2(.din(rotw3[23:16]), .dout(sub31));
     Sbox_LUT x3(.din(rotw3[15:8]), .dout(sub32));
     Sbox_LUT x4(.din(rotw3[7:0]), .dout(sub33));
     
     assign temp = rcon ^ {sub30,sub31,sub32,sub33};//Rcon Operation
     
     assign w0_out = W0 ^ temp;
     assign w1_out = W1 ^ w0_out;
     assign w2_out = W2 ^ w1_out;
     assign w3_out = W3 ^ w2_out;
     
     assign keyout = {w0_out, w1_out, w2_out, w3_out};
       
endmodule
